spring:
  application:
    name: eureka-server

  config:
    import: "configserver:"

  cloud:
    config:
      uri: ${CONFIG_URI}
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}